---
#Sensor details
sensor:
 menu-cfg:
    source_file: menu
    source_file_ext: .cfg
    source_location: /workspace/OSSIM/rebranding/May-2017/rebranded/
    dest_file: menu
    dest_file_ext: .ctr
    items_list: [label,text,confirm,menus,info,cmd,next,next_else]
    replace_what: AlienVault
    replace_with: Securmatic
 menu-network-cfg:
   source_file: menu_network
   source_file_ext: .cfg
   source_location: /workspace/OSSIM/rebranding/May-2017/rebranded/
   dest_file: menu_network
   dest_file_ext: .ctr
   items_list: [label,title,text,confirm,menus,info,cmd,next,next_else]
   replace_what: AlienVault
   replace_with: Securmatic
 ossim-setup:
  source_file: ossim_setup
  source_file_ext: .conf
  source_location: /workspace/OSSIM/rebranding/May-2017/rebranded/
  dest_file: ossim_setup
  dest_file_ext: .ctr
  items_list: [domain,hostname]
  replace_what: alienvault
  replace_with: securmatic
 issue:
  source_file: issue
  source_file_ext:
  source_location: /workspace/OSSIM/rebranding/May-2017/rebranded/etc.issue/
  dest_file: issue
  dest_file_ext: .ctr
  items_list: []
  replace_what: AlienVault,alienvault
  replace_with: Securmatic,securmatic
 motd-tail:
  source_file: motd.tail
  source_file_ext:
  source_location: /workspace/OSSIM/rebranding/May-2017/rebranded/etc.issue/
  dest_file: motd.tail
  dest_file_ext: .ctr
  items_list: []
  replace_what: AlienVault,alienvault
  replace_with: Securmatic,securmatic
 hostname:
  source_file: hostname
  source_file_ext:
  source_location: /workspace/OSSIM/rebranding/May-2017/rebranded/etc.hosts/
  dest_file: hostname
  dest_file_ext: .ctr
  replace_what: AlienVault,alienvault
  replace_with: Securmatic,securmatic
 hosts:
  source_file: hosts
  source_file_ext:
  source_location: /workspace/OSSIM/rebranding/May-2017/rebranded/etc.hosts/
  dest_file: hosts
  dest_file_ext: .ctr
  replace_what: AlienVault,alienvault
  replace_with: Securmatic,securmatic

config:
 debug: on
 log: true
 log_location: \opt\rebrand
 log_name: rebrand_log.log
 format: '%d-%t-%f-%l'
