---
#Sensor details
sensor:
 source_file: menu.cfg
 source_location: /workspace/OSSIM/rebranding/May-2017/rebranded
 items_list: [label,text,confirm,menus,info,]
 replace_what: Alienvault
 replace_with: Securmatic
config:
 debug: on
 log: true
 log_location: \opt\rebrand
 log_name: rebrand_log.log
 format: '%d-%t-%f-%l'